export const FUND_LISTS_REQUEST = 'FUND_LISTS_REQUEST ';
export const FUND_LISTS_SUCCESS = 'FUND_LISTS_SUCCESS ';
export const FUND_LISTS_FAIL = 'FUND_LISTS_FAIL ';

export const FUND_DETAILS_REQUEST = 'FUND_DETAILS_REQUEST';
export const FUND_DETAILS_SUCCESS = 'FUND_DETAILS_SUCCESS';
export const FUND_DETAILS_FAIL = 'FUND_DETAILS_FAIL';
